version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongocsharpdriver
    versions:
    - 2.11.6
  - dependency-name: MongoDB.Driver
    versions:
    - 2.11.5
  - dependency-name: MongoDB.Bson
    versions:
    - 2.11.2
